-- ============================================================
-- VARS — Seed Data (V2)
-- service_categories and services tables were removed in
-- migration 20260603000001_service_taxonomy_v2.sql.
-- Vendor services are now free-name entries created by vendors
-- during onboarding — no platform-defined seed data needed.
-- ============================================================
