// ============================================================
// VARS — unsubscribe-lead
// GET ?id=<lead_id>&t=<token>
//
// Verifies HMAC-SHA256 token, marks email_unsubscribed = true
// on vendor_leads.
//
// UNSUBSCRIBE_SECRET must be set in Supabase secrets.
// Token is generated by send-marketing-email using the same secret.
// ============================================================

import { createAdminClient } from '../_shared/supabase.ts';

const UNSUBSCRIBE_SECRET = Deno.env.get('UNSUBSCRIBE_SECRET') ?? '';

async function makeToken(leadId: string): Promise<string> {
  const enc = new TextEncoder();
  const key = await crypto.subtle.importKey(
    'raw',
    enc.encode(UNSUBSCRIBE_SECRET),
    { name: 'HMAC', hash: 'SHA-256' },
    false,
    ['sign'],
  );
  const sig = await crypto.subtle.sign('HMAC', key, enc.encode(leadId));
  return btoa(String.fromCharCode(...new Uint8Array(sig)))
    .replace(/\+/g, '-').replace(/\//g, '_').replace(/=/g, '');
}

const html = (msg: string, sub = '') => `<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><title>${msg}</title></head>
<body style="font-family:'Helvetica Neue',sans-serif;max-width:480px;margin:60px auto;text-align:center;color:#374151;padding:0 24px;">
  <p style="font-size:18px;font-weight:700;margin-bottom:8px;">${msg}</p>
  ${sub ? `<p style="color:#6b7280;margin:0;">${sub}</p>` : ''}
  <p style="margin-top:40px;font-size:13px;color:#9ca3af;"><a href="https://bookwithvars.com" style="color:#9ca3af;">bookwithvars.com</a></p>
</body></html>`;

Deno.serve(async (req: Request) => {
  const url    = new URL(req.url);
  const leadId = url.searchParams.get('id') ?? '';
  const token  = url.searchParams.get('t')  ?? '';

  if (!leadId || !token || !UNSUBSCRIBE_SECRET) {
    return new Response(html('Invalid unsubscribe link.'), {
      status: 400, headers: { 'Content-Type': 'text/html' },
    });
  }

  const expected = await makeToken(leadId);
  if (token !== expected) {
    return new Response(html('Invalid unsubscribe link.'), {
      status: 400, headers: { 'Content-Type': 'text/html' },
    });
  }

  const db = createAdminClient();
  const { data: lead, error } = await db
    .from('vendor_leads')
    .update({ email_unsubscribed: true })
    .eq('id', leadId)
    .select('email')
    .single();

  if (error || !lead) {
    console.error('[unsubscribe-lead] update failed:', error?.message);
    return new Response(
      html('Something went wrong.', 'Please email hello@bookwithvars.com to unsubscribe.'),
      { status: 500, headers: { 'Content-Type': 'text/html' } },
    );
  }

  console.log('[unsubscribe-lead] unsubscribed:', lead.email);
  return new Response(
    html("You've been unsubscribed.", "You won't receive marketing emails from VARS at this address."),
    { status: 200, headers: { 'Content-Type': 'text/html' } },
  );
});
