import React from 'react';
import {
  ArrowUpIcon,
  BanknoteIcon,
  BellIcon,
  BriefcaseIcon,
  CalendarIcon,
  CarIcon,
  CheckCircleIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  ClockIcon,
  CloseIcon,
  CreditCardIcon,
  EditIcon,
  EyeIcon,
  EyeOffIcon,
  GearIcon,
  HeartIcon,
  HourglassIcon,
  LightningIcon,
  LockIcon,
  PenLineIcon,
  PersonIcon,
  PinIcon,
  PlusIcon,
  SearchIcon,
  SparkleIcon,
  StarEmptyIcon,
  StarFilledIcon,
  StarIcon,
  WarningIcon,
  XCircleIcon,
} from '@/components/icons';

// ios: verified against sf-symbols-typescript's SFSymbol union (all 33 present).
// android: verified against @expo/vector-icons MaterialIcons glyph map (all 33 present,
// hyphenated names — this is the classic Material Icons font, not Material Symbols;
// see the Icon system row in docs/VARS_PROJECT_CONTEXT.md for why).
export const iconSystemNames = {
  add: { ios: 'plus', android: 'add' },
  arrowUp: { ios: 'arrow.up', android: 'arrow-upward' },
  banknote: { ios: 'banknote', android: 'payments' },
  bell: { ios: 'bell', android: 'notifications' },
  briefcase: { ios: 'briefcase', android: 'work' },
  calendar: { ios: 'calendar', android: 'calendar-month' },
  car: { ios: 'car', android: 'directions-car' },
  check: { ios: 'checkmark', android: 'check' },
  checkCircle: { ios: 'checkmark.circle', android: 'check-circle' },
  chevronDown: { ios: 'chevron.down', android: 'keyboard-arrow-down' },
  chevronRight: { ios: 'chevron.right', android: 'chevron-right' },
  chevronUp: { ios: 'chevron.up', android: 'keyboard-arrow-up' },
  clock: { ios: 'clock', android: 'schedule' },
  close: { ios: 'xmark', android: 'close' },
  creditCard: { ios: 'creditcard', android: 'credit-card' },
  edit: { ios: 'square.and.pencil', android: 'edit' },
  eye: { ios: 'eye', android: 'visibility' },
  eyeOff: { ios: 'eye.slash', android: 'visibility-off' },
  gear: { ios: 'gearshape', android: 'settings' },
  heart: { ios: 'heart', android: 'favorite' },
  hourglass: { ios: 'hourglass', android: 'hourglass-empty' },
  lightning: { ios: 'bolt', android: 'bolt' },
  lock: { ios: 'lock', android: 'lock' },
  penLine: { ios: 'pencil.line', android: 'edit-note' },
  person: { ios: 'person', android: 'person' },
  pin: { ios: 'mappin', android: 'location-on' },
  search: { ios: 'magnifyingglass', android: 'search' },
  sparkle: { ios: 'sparkles', android: 'auto-awesome' },
  star: { ios: 'star', android: 'star' },
  starFilled: { ios: 'star.fill', android: 'star' },
  starEmpty: { ios: 'star', android: 'star-border' },
  warning: { ios: 'exclamationmark.triangle', android: 'warning' },
  xCircle: { ios: 'xmark.circle', android: 'cancel' },
} as const;

export type VarsIconName = keyof typeof iconSystemNames;

export const SvgIconByName: Record<VarsIconName, React.ComponentType<{ size?: number; color?: string }>> = {
  add: PlusIcon,
  arrowUp: ArrowUpIcon,
  banknote: BanknoteIcon,
  bell: BellIcon,
  briefcase: BriefcaseIcon,
  calendar: CalendarIcon,
  car: CarIcon,
  check: CheckIcon,
  checkCircle: CheckCircleIcon,
  chevronDown: ChevronDownIcon,
  chevronRight: ChevronRightIcon,
  chevronUp: ChevronUpIcon,
  clock: ClockIcon,
  close: CloseIcon,
  creditCard: CreditCardIcon,
  edit: EditIcon,
  eye: EyeIcon,
  eyeOff: EyeOffIcon,
  gear: GearIcon,
  heart: HeartIcon,
  hourglass: HourglassIcon,
  lightning: LightningIcon,
  lock: LockIcon,
  penLine: PenLineIcon,
  person: PersonIcon,
  pin: PinIcon,
  search: SearchIcon,
  sparkle: SparkleIcon,
  star: StarIcon,
  starFilled: StarFilledIcon,
  starEmpty: StarEmptyIcon,
  warning: WarningIcon,
  xCircle: XCircleIcon,
};
